/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AccessLevelSchema extends BaseModel {
  static $columns = ['color', 'createdAt', 'id', 'isDefault', 'name', 'sortOrder', 'updatedAt'] as const
  $columns = AccessLevelSchema.$columns
  @column()
  declare color: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isDefault: boolean
  @column()
  declare name: string
  @column()
  declare sortOrder: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class AppConfigSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'group', 'id', 'key', 'label', 'type', 'updatedAt', 'value'] as const
  $columns = AppConfigSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column()
  declare group: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare key: string
  @column()
  declare label: string | null
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare value: string | null
}

export class AssessmentQuestionSchema extends BaseModel {
  static $columns = ['assessmentId', 'correctAnswer', 'createdAt', 'id', 'optionA', 'optionB', 'optionC', 'optionD', 'question', 'sortOrder', 'updatedAt'] as const
  $columns = AssessmentQuestionSchema.$columns
  @column()
  declare assessmentId: string
  @column()
  declare correctAnswer: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare optionA: string
  @column()
  declare optionB: string
  @column()
  declare optionC: string
  @column()
  declare optionD: string
  @column()
  declare question: string
  @column()
  declare sortOrder: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class AssessmentResultSchema extends BaseModel {
  static $columns = ['answers', 'assessmentId', 'completedAt', 'id', 'score', 'total', 'userId'] as const
  $columns = AssessmentResultSchema.$columns
  @column()
  declare answers: any | null
  @column()
  declare assessmentId: string
  @column.dateTime()
  declare completedAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare score: number
  @column()
  declare total: number
  @column()
  declare userId: string
}

export class AssessmentSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'postId', 'updatedAt'] as const
  $columns = AssessmentSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare postId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class AssetPostSchema extends BaseModel {
  static $columns = ['assetId', 'createdAt', 'id', 'postId', 'sortOrder', 'updatedAt'] as const
  $columns = AssetPostSchema.$columns
  @column()
  declare assetId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare postId: string
  @column()
  declare sortOrder: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class AssetSchema extends BaseModel {
  static $columns = ['altText', 'asset', 'createdAt', 'credit', 'id', 'type', 'updatedAt'] as const
  $columns = AssetSchema.$columns
  @column()
  declare altText: string
  @column()
  declare asset: any
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare credit: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class AuthAttemptSchema extends BaseModel {
  static $columns = ['createdAt', 'deletedAt', 'id', 'purpose', 'uid', 'updatedAt'] as const
  $columns = AuthAttemptSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare purpose: string
  @column()
  declare uid: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class AuthorPostSchema extends BaseModel {
  static $columns = ['authorTypeId', 'createdAt', 'id', 'postId', 'updatedAt', 'userId'] as const
  $columns = AuthorPostSchema.$columns
  @column()
  declare authorTypeId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare postId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string
}

export class BlockSchema extends BaseModel {
  static $columns = ['createdAt', 'expiresAt', 'id', 'ipAddress', 'reason', 'sectionId', 'updatedAt', 'userId'] as const
  $columns = BlockSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare ipAddress: string
  @column()
  declare reason: string | null
  @column()
  declare sectionId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string | null
}

export class CandidateApplicationSchema extends BaseModel {
  static $columns = ['adminRemarks', 'age', 'certificate10Th', 'certificate12Th', 'certificateGraduation', 'certificatePostGraduation', 'createdAt', 'educationalQualification', 'fullName', 'gender', 'id', 'introductionVideo', 'kycDocument', 'kycType', 'passportPhoto', 'phone', 'purposeDescription', 'purposeVideo', 'reviewedAt', 'reviewedBy', 'status', 'updatedAt', 'userId'] as const
  $columns = CandidateApplicationSchema.$columns
  @column()
  declare adminRemarks: string | null
  @column()
  declare age: number | null
  @column()
  declare certificate10Th: any | null
  @column()
  declare certificate12Th: any | null
  @column()
  declare certificateGraduation: any | null
  @column()
  declare certificatePostGraduation: any | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare educationalQualification: string | null
  @column()
  declare fullName: string | null
  @column()
  declare gender: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare introductionVideo: any | null
  @column()
  declare kycDocument: any | null
  @column()
  declare kycType: string | null
  @column()
  declare passportPhoto: any | null
  @column()
  declare phone: string | null
  @column()
  declare purposeDescription: string | null
  @column()
  declare purposeVideo: any | null
  @column.dateTime()
  declare reviewedAt: DateTime | null
  @column()
  declare reviewedBy: string | null
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: string
}

export class CommentVoteSchema extends BaseModel {
  static $columns = ['commentId', 'createdAt', 'id', 'updatedAt', 'userId'] as const
  $columns = CommentVoteSchema.$columns
  @column()
  declare commentId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string
}

export class CommentSchema extends BaseModel {
  static $columns = ['body', 'createdAt', 'discussionId', 'id', 'identity', 'levelIndex', 'name', 'postId', 'replyTo', 'rootParentId', 'stateId', 'type', 'updatedAt', 'userId'] as const
  $columns = CommentSchema.$columns
  @column()
  declare body: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare discussionId: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare identity: string
  @column()
  declare levelIndex: number
  @column()
  declare name: string | null
  @column()
  declare postId: string | null
  @column()
  declare replyTo: string | null
  @column()
  declare rootParentId: string | null
  @column()
  declare stateId: number
  @column()
  declare type: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string | null
}

export class CourseModulePostSchema extends BaseModel {
  static $columns = ['courseModuleId', 'createdAt', 'id', 'postId', 'sortOrder', 'updatedAt'] as const
  $columns = CourseModulePostSchema.$columns
  @column()
  declare courseModuleId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare postId: string
  @column()
  declare sortOrder: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class CourseModuleSchema extends BaseModel {
  static $columns = ['courseId', 'createdAt', 'id', 'name', 'notes', 'sortOrder', 'state', 'updatedAt'] as const
  $columns = CourseModuleSchema.$columns
  @column()
  declare courseId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column()
  declare notes: string | null
  @column()
  declare sortOrder: number
  @column()
  declare state: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class CourseTaxonomySchema extends BaseModel {
  static $columns = ['courseId', 'createdAt', 'id', 'sortOrder', 'taxonomyId', 'updatedAt'] as const
  $columns = CourseTaxonomySchema.$columns
  @column()
  declare courseId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare sortOrder: number
  @column()
  declare taxonomyId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class CourseSchema extends BaseModel {
  static $columns = ['accessLevelId', 'assetId', 'createdAt', 'description', 'difficulty', 'enrollmentAttemptLimit', 'id', 'isFeatured', 'metaDescription', 'name', 'ownerId', 'pageTitle', 'slug', 'sortOrder', 'state', 'updatedAt'] as const
  $columns = CourseSchema.$columns
  @column()
  declare accessLevelId: string | null
  @column()
  declare assetId: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string
  @column()
  declare difficulty: string
  @column()
  declare enrollmentAttemptLimit: number
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isFeatured: boolean
  @column()
  declare metaDescription: string
  @column()
  declare name: string
  @column()
  declare ownerId: string | null
  @column()
  declare pageTitle: string
  @column()
  declare slug: string
  @column()
  declare sortOrder: number
  @column()
  declare state: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class DiscussionViewSchema extends BaseModel {
  static $columns = ['createdAt', 'discussionId', 'id', 'ipAddress', 'typeId', 'updatedAt', 'userAgent', 'userId'] as const
  $columns = DiscussionViewSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare discussionId: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare ipAddress: string
  @column()
  declare typeId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userAgent: string
  @column()
  declare userId: string | null
}

export class DiscussionVoteSchema extends BaseModel {
  static $columns = ['createdAt', 'discussionId', 'id', 'updatedAt', 'userId'] as const
  $columns = DiscussionVoteSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare discussionId: string | null
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string | null
}

export class DiscussionSchema extends BaseModel {
  static $columns = ['body', 'createdAt', 'id', 'slug', 'solvedAt', 'solvedCommentId', 'stateId', 'taxonomyId', 'title', 'updatedAt', 'userId', 'views'] as const
  $columns = DiscussionSchema.$columns
  @column()
  declare body: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare slug: string
  @column.dateTime()
  declare solvedAt: DateTime | null
  @column()
  declare solvedCommentId: string | null
  @column()
  declare stateId: number
  @column()
  declare taxonomyId: string | null
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string
  @column()
  declare views: number
}

export class EmailHistorySchema extends BaseModel {
  static $columns = ['createdAt', 'emailFrom', 'emailTo', 'id', 'updatedAt', 'userId'] as const
  $columns = EmailHistorySchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare emailFrom: string
  @column()
  declare emailTo: string
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string
}

export class HistorySchema extends BaseModel {
  static $columns = ['createdAt', 'historyTypeId', 'id', 'isCompleted', 'postId', 'readPercent', 'route', 'taxonomyId', 'updatedAt', 'userId', 'watchPercent', 'watchSeconds'] as const
  $columns = HistorySchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare historyTypeId: number
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isCompleted: boolean
  @column()
  declare postId: string | null
  @column()
  declare readPercent: number | null
  @column()
  declare route: string
  @column()
  declare taxonomyId: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string
  @column()
  declare watchPercent: number | null
  @column()
  declare watchSeconds: number
}

export class LessonRequestSchema extends BaseModel {
  static $columns = ['body', 'createdAt', 'id', 'name', 'priority', 'stateId', 'updatedAt', 'userId'] as const
  $columns = LessonRequestSchema.$columns
  @column()
  declare body: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column()
  declare priority: number
  @column()
  declare stateId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string
}

export class MemberEnrollmentEventSchema extends BaseModel {
  static $columns = ['actorId', 'createdAt', 'eventType', 'fromStatus', 'id', 'memberEnrollmentId', 'note', 'snapshot', 'toStatus'] as const
  $columns = MemberEnrollmentEventSchema.$columns
  @column()
  declare actorId: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare eventType: string
  @column()
  declare fromStatus: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare memberEnrollmentId: string
  @column()
  declare note: string | null
  @column()
  declare snapshot: any | null
  @column()
  declare toStatus: string | null
}

export class MemberEnrollmentSchema extends BaseModel {
  static $columns = ['attemptNumber', 'contextLinks', 'createdAt', 'id', 'reason', 'rejectionReason', 'resourceId', 'resourceType', 'reviewedAt', 'reviewerId', 'revocationReason', 'revokedAt', 'revokedById', 'status', 'updatedAt', 'userId', 'videoFile', 'videoSource', 'videoUrl'] as const
  $columns = MemberEnrollmentSchema.$columns
  @column()
  declare attemptNumber: number
  @column()
  declare contextLinks: any | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare reason: string
  @column()
  declare rejectionReason: string | null
  @column()
  declare resourceId: string
  @column()
  declare resourceType: string
  @column.dateTime()
  declare reviewedAt: DateTime | null
  @column()
  declare reviewerId: string | null
  @column()
  declare revocationReason: string | null
  @column.dateTime()
  declare revokedAt: DateTime | null
  @column()
  declare revokedById: string | null
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string
  @column()
  declare videoFile: any | null
  @column()
  declare videoSource: string
  @column()
  declare videoUrl: string | null
}

export class NotificationSchema extends BaseModel {
  static $columns = ['actionedAt', 'body', 'createdAt', 'global', 'href', 'id', 'initiatorUserId', 'notificationTypeId', 'readAt', 'tableId', 'tableName', 'title', 'updatedAt', 'userId'] as const
  $columns = NotificationSchema.$columns
  @column.dateTime()
  declare actionedAt: DateTime | null
  @column()
  declare body: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare global: boolean
  @column()
  declare href: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare initiatorUserId: string | null
  @column()
  declare notificationTypeId: number
  @column.dateTime()
  declare readAt: DateTime | null
  @column()
  declare tableId: string | null
  @column()
  declare tableName: string | null
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string
}

export class PathCourseSchema extends BaseModel {
  static $columns = ['courseId', 'createdAt', 'id', 'pathId', 'sortOrder', 'updatedAt'] as const
  $columns = PathCourseSchema.$columns
  @column()
  declare courseId: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare pathId: string | null
  @column()
  declare sortOrder: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class PathSchema extends BaseModel {
  static $columns = ['assetId', 'createdAt', 'description', 'id', 'isFeatured', 'name', 'ownerId', 'slug', 'state', 'updatedAt'] as const
  $columns = PathSchema.$columns
  @column()
  declare assetId: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isFeatured: boolean
  @column()
  declare name: string
  @column()
  declare ownerId: string | null
  @column()
  declare slug: string
  @column()
  declare state: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class PlaylistPostSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'playlistId', 'postId', 'sortOrder', 'updatedAt'] as const
  $columns = PlaylistPostSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare playlistId: string | null
  @column()
  declare postId: string | null
  @column()
  declare sortOrder: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class PlaylistSchema extends BaseModel {
  static $columns = ['assetId', 'createdAt', 'description', 'id', 'isFeatured', 'name', 'ownerId', 'slug', 'state', 'updatedAt'] as const
  $columns = PlaylistSchema.$columns
  @column()
  declare assetId: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isFeatured: boolean
  @column()
  declare name: string
  @column()
  declare ownerId: string | null
  @column()
  declare slug: string
  @column()
  declare state: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class PostCaptionSchema extends BaseModel {
  static $columns = ['createdAt', 'filename', 'id', 'label', 'language', 'postId', 'sortOrder', 'type', 'updatedAt'] as const
  $columns = PostCaptionSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare filename: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare label: string
  @column()
  declare language: string
  @column()
  declare postId: string
  @column()
  declare sortOrder: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class PostChapterSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'postId', 'sortOrder', 'time', 'title', 'updatedAt'] as const
  $columns = PostChapterSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare postId: string
  @column()
  declare sortOrder: number
  @column()
  declare time: number
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class PostSnapshotSchema extends BaseModel {
  static $columns = ['body', 'canonical', 'createdAt', 'deletedAt', 'description', 'id', 'isFeatured', 'isPersonal', 'metaDescription', 'pageTitle', 'postId', 'publishAtUser', 'publishedAt', 'revisedBy', 'revision', 'revisionDate', 'slug', 'stateId', 'timezone', 'title', 'updatedAt', 'videoUrl', 'viewCount', 'viewCountUnique'] as const
  $columns = PostSnapshotSchema.$columns
  @column()
  declare body: string | null
  @column()
  declare canonical: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isFeatured: boolean | null
  @column()
  declare isPersonal: boolean | null
  @column()
  declare metaDescription: string | null
  @column()
  declare pageTitle: string | null
  @column()
  declare postId: string
  @column()
  declare publishAtUser: string | null
  @column.dateTime()
  declare publishedAt: DateTime | null
  @column()
  declare revisedBy: number
  @column()
  declare revision: number
  @column.dateTime()
  declare revisionDate: DateTime
  @column()
  declare slug: string
  @column()
  declare stateId: number
  @column()
  declare timezone: string | null
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare videoUrl: string | null
  @column()
  declare viewCount: number
  @column()
  declare viewCountUnique: number
}

export class PostTaxonomySchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'postId', 'sortOrder', 'taxonomyId', 'updatedAt'] as const
  $columns = PostTaxonomySchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare postId: string | null
  @column()
  declare sortOrder: number
  @column()
  declare taxonomyId: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class PostTopicSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'postId', 'sortOrder', 'topicId', 'updatedAt'] as const
  $columns = PostTopicSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare postId: string
  @column()
  declare sortOrder: number
  @column()
  declare topicId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class PostSchema extends BaseModel {
  static $columns = ['body', 'bodyBlocks', 'bodyType', 'canonical', 'createdAt', 'description', 'id', 'isFeatured', 'isLivestream', 'isPersonal', 'isWatchlistSent', 'livestreamUrl', 'metaDescription', 'pageTitle', 'postType', 'publishedAt', 'publishedAtUser', 'ragAddedAt', 'readMinutes', 'readTime', 'redirectUrl', 'repositoryAccessLevel', 'repositoryUrl', 'slug', 'state', 'timezone', 'title', 'updatedAt', 'updatedContentAt', 'videoBunnyId', 'videoSeconds', 'videoType', 'videoUrl', 'viewCount', 'viewCountUnique', 'wordCount'] as const
  $columns = PostSchema.$columns
  @column()
  declare body: string | null
  @column()
  declare bodyBlocks: any | null
  @column()
  declare bodyType: string
  @column()
  declare canonical: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isFeatured: boolean
  @column()
  declare isLivestream: boolean
  @column()
  declare isPersonal: boolean
  @column()
  declare isWatchlistSent: boolean
  @column()
  declare livestreamUrl: string | null
  @column()
  declare metaDescription: string | null
  @column()
  declare pageTitle: string | null
  @column()
  declare postType: string
  @column.dateTime()
  declare publishedAt: DateTime | null
  @column.dateTime()
  declare publishedAtUser: DateTime | null
  @column.dateTime()
  declare ragAddedAt: DateTime | null
  @column()
  declare readMinutes: number
  @column()
  declare readTime: number
  @column()
  declare redirectUrl: string | null
  @column()
  declare repositoryAccessLevel: number
  @column()
  declare repositoryUrl: string | null
  @column()
  declare slug: string
  @column()
  declare state: string
  @column()
  declare timezone: string | null
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column.dateTime()
  declare updatedContentAt: DateTime | null
  @column()
  declare videoBunnyId: string | null
  @column()
  declare videoSeconds: number
  @column()
  declare videoType: string
  @column()
  declare videoUrl: string | null
  @column()
  declare viewCount: number
  @column()
  declare viewCountUnique: number
  @column()
  declare wordCount: number
}

export class ProfileSchema extends BaseModel {
  static $columns = ['biography', 'blueskyUrl', 'company', 'createdAt', 'emailOnAchievement', 'emailOnComment', 'emailOnCommentReply', 'emailOnMention', 'emailOnNewDeviceLogin', 'emailOnWatchlist', 'facebookUrl', 'githubUrl', 'id', 'instagramUrl', 'linkedinUrl', 'location', 'name', 'threadsUrl', 'twitterUrl', 'updatedAt', 'website', 'youtubeUrl'] as const
  $columns = ProfileSchema.$columns
  @column()
  declare biography: string | null
  @column()
  declare blueskyUrl: string | null
  @column()
  declare company: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare emailOnAchievement: boolean
  @column()
  declare emailOnComment: boolean
  @column()
  declare emailOnCommentReply: boolean
  @column()
  declare emailOnMention: boolean
  @column()
  declare emailOnNewDeviceLogin: boolean
  @column()
  declare emailOnWatchlist: boolean
  @column()
  declare facebookUrl: string | null
  @column()
  declare githubUrl: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare instagramUrl: string | null
  @column()
  declare linkedinUrl: string | null
  @column()
  declare location: string | null
  @column()
  declare name: string | null
  @column()
  declare threadsUrl: string | null
  @column()
  declare twitterUrl: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare website: string | null
  @column()
  declare youtubeUrl: string | null
}

export class ProgressSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'isCompleted', 'postId', 'readPercent', 'updatedAt', 'userId', 'watchPercent', 'watchSeconds'] as const
  $columns = ProgressSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isCompleted: boolean
  @column()
  declare postId: string | null
  @column()
  declare readPercent: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string
  @column()
  declare watchPercent: number | null
  @column()
  declare watchSeconds: number
}

export class QuestionVoteSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'questionId', 'updatedAt', 'userId'] as const
  $columns = QuestionVoteSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare questionId: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string | null
}

export class QuestionSchema extends BaseModel {
  static $columns = ['body', 'createdAt', 'id', 'title', 'updatedAt', 'userId'] as const
  $columns = QuestionSchema.$columns
  @column()
  declare body: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string | null
}

export class RateLimitSchema extends BaseModel {
  static $columns = ['expire', 'key', 'points'] as const
  $columns = RateLimitSchema.$columns
  @column()
  declare expire: bigint | number | null
  @column({ isPrimary: true })
  declare key: string
  @column()
  declare points: number
}

export class RememberMeTokenSchema extends BaseModel {
  static $columns = ['createdAt', 'expiresAt', 'hash', 'id', 'tokenableId', 'updatedAt'] as const
  $columns = RememberMeTokenSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare tokenableId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class RequestVoteSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'lessonRequestId', 'updatedAt', 'userId'] as const
  $columns = RequestVoteSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare lessonRequestId: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string | null
}

export class RoleSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'id', 'name', 'updatedAt'] as const
  $columns = RoleSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class SeriesSchema extends BaseModel {
  static $columns = ['accessLevelId', 'assetId', 'createdAt', 'description', 'enrollmentAttemptLimit', 'id', 'isFeatured', 'name', 'ownerId', 'slug', 'sortOrder', 'state', 'updatedAt'] as const
  $columns = SeriesSchema.$columns
  @column()
  declare accessLevelId: string | null
  @column()
  declare assetId: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string
  @column()
  declare enrollmentAttemptLimit: number
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isFeatured: boolean
  @column()
  declare name: string
  @column()
  declare ownerId: string | null
  @column()
  declare slug: string
  @column()
  declare sortOrder: number
  @column()
  declare state: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class SeriesPostSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'postId', 'seriesId', 'sortOrder', 'updatedAt'] as const
  $columns = SeriesPostSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare postId: string | null
  @column()
  declare seriesId: string | null
  @column()
  declare sortOrder: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class SeriesTaxonomySchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'seriesId', 'sortOrder', 'taxonomyId', 'updatedAt'] as const
  $columns = SeriesTaxonomySchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare seriesId: string
  @column()
  declare sortOrder: number
  @column()
  declare taxonomyId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class SessionLogSchema extends BaseModel {
  static $columns = ['browserEngine', 'browserName', 'browserVersion', 'city', 'country', 'countryCode', 'createdAt', 'deviceModel', 'deviceType', 'deviceVendor', 'forceLogout', 'id', 'ipAddress', 'lastTouchedAt', 'loginAt', 'loginSuccessful', 'logoutAt', 'osName', 'osVersion', 'sessionId', 'token', 'updatedAt', 'userAgent', 'userId'] as const
  $columns = SessionLogSchema.$columns
  @column()
  declare browserEngine: string | null
  @column()
  declare browserName: string | null
  @column()
  declare browserVersion: string | null
  @column()
  declare city: string | null
  @column()
  declare country: string | null
  @column()
  declare countryCode: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare deviceModel: string | null
  @column()
  declare deviceType: string | null
  @column()
  declare deviceVendor: string | null
  @column()
  declare forceLogout: boolean
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare ipAddress: string | null
  @column.dateTime()
  declare lastTouchedAt: DateTime | null
  @column.dateTime()
  declare loginAt: DateTime | null
  @column()
  declare loginSuccessful: boolean
  @column.dateTime()
  declare logoutAt: DateTime | null
  @column()
  declare osName: string | null
  @column()
  declare osVersion: string | null
  @column()
  declare sessionId: string
  @column()
  declare token: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userAgent: string | null
  @column()
  declare userId: string
}

export class TaxonomySchema extends BaseModel {
  static $columns = ['assetId', 'createdAt', 'description', 'id', 'isFeatured', 'levelIndex', 'metaDescription', 'name', 'ownerId', 'pageTitle', 'parentId', 'rootParentId', 'slug', 'type', 'updatedAt'] as const
  $columns = TaxonomySchema.$columns
  @column()
  declare assetId: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isFeatured: boolean
  @column()
  declare levelIndex: number | null
  @column()
  declare metaDescription: string
  @column()
  declare name: string
  @column()
  declare ownerId: string
  @column()
  declare pageTitle: string
  @column()
  declare parentId: string | null
  @column()
  declare rootParentId: string | null
  @column()
  declare slug: string
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class TopicSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'isFeatured', 'name', 'slug', 'updatedAt', 'userId'] as const
  $columns = TopicSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isFeatured: boolean
  @column()
  declare name: string
  @column()
  declare slug: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: string
}

export class UserSchema extends BaseModel {
  static $columns = ['avatar', 'createdAt', 'defaultLessonPanel', 'email', 'emailVerifiedAt', 'googleEmail', 'googleId', 'id', 'isEnabledAutoplayNext', 'isEnabledMentions', 'isEnabledMiniPlayer', 'isEnabledProfile', 'isEnabledTranscript', 'lastLoginAt', 'password', 'roleId', 'theme', 'updatedAt', 'username'] as const
  $columns = UserSchema.$columns
  @column()
  declare avatar: any | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare defaultLessonPanel: string
  @column()
  declare email: string
  @column.dateTime()
  declare emailVerifiedAt: DateTime | null
  @column()
  declare googleEmail: string | null
  @column()
  declare googleId: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isEnabledAutoplayNext: boolean
  @column()
  declare isEnabledMentions: boolean | null
  @column()
  declare isEnabledMiniPlayer: boolean
  @column()
  declare isEnabledProfile: boolean
  @column()
  declare isEnabledTranscript: boolean
  @column.dateTime()
  declare lastLoginAt: DateTime | null
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare roleId: string
  @column()
  declare theme: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare username: string
}

export class WatchlistSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'postId', 'taxonomyId', 'updatedAt', 'userId'] as const
  $columns = WatchlistSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare postId: string | null
  @column()
  declare taxonomyId: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string
}
