/* eslint-disable prettier/prettier */
import type { AdonisEndpoint } from '@tuyau/core/types'
import type { Registry } from './schema.d.ts'
import type { ApiDefinition } from './tree.d.ts'

const placeholder: any = {}

const routes = {
  'drive.fs.serve': {
    methods: ["GET","HEAD"],
    pattern: '/uploads/*',
    tokens: [{"old":"/uploads/*","type":0,"val":"uploads","end":""},{"old":"/uploads/*","type":2,"val":"*","end":""}],
    types: placeholder as Registry['drive.fs.serve']['types'],
  },
  'admin.dashboard.index': {
    methods: ["GET","HEAD"],
    pattern: '/admin/dashboard',
    tokens: [{"old":"/admin/dashboard","type":0,"val":"admin","end":""},{"old":"/admin/dashboard","type":0,"val":"dashboard","end":""}],
    types: placeholder as Registry['admin.dashboard.index']['types'],
  },
  'admin.posts.index': {
    methods: ["GET","HEAD"],
    pattern: '/admin/posts',
    tokens: [{"old":"/admin/posts","type":0,"val":"admin","end":""},{"old":"/admin/posts","type":0,"val":"posts","end":""}],
    types: placeholder as Registry['admin.posts.index']['types'],
  },
  'admin.posts.create': {
    methods: ["GET","HEAD"],
    pattern: '/admin/posts/create',
    tokens: [{"old":"/admin/posts/create","type":0,"val":"admin","end":""},{"old":"/admin/posts/create","type":0,"val":"posts","end":""},{"old":"/admin/posts/create","type":0,"val":"create","end":""}],
    types: placeholder as Registry['admin.posts.create']['types'],
  },
  'admin.posts.store': {
    methods: ["POST"],
    pattern: '/admin/posts',
    tokens: [{"old":"/admin/posts","type":0,"val":"admin","end":""},{"old":"/admin/posts","type":0,"val":"posts","end":""}],
    types: placeholder as Registry['admin.posts.store']['types'],
  },
  'admin.posts.edit': {
    methods: ["GET","HEAD"],
    pattern: '/admin/posts/:id/edit',
    tokens: [{"old":"/admin/posts/:id/edit","type":0,"val":"admin","end":""},{"old":"/admin/posts/:id/edit","type":0,"val":"posts","end":""},{"old":"/admin/posts/:id/edit","type":1,"val":"id","end":""},{"old":"/admin/posts/:id/edit","type":0,"val":"edit","end":""}],
    types: placeholder as Registry['admin.posts.edit']['types'],
  },
  'admin.posts.update': {
    methods: ["PUT","PATCH"],
    pattern: '/admin/posts/:id',
    tokens: [{"old":"/admin/posts/:id","type":0,"val":"admin","end":""},{"old":"/admin/posts/:id","type":0,"val":"posts","end":""},{"old":"/admin/posts/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.posts.update']['types'],
  },
  'admin.posts.destroy': {
    methods: ["DELETE"],
    pattern: '/admin/posts/:id',
    tokens: [{"old":"/admin/posts/:id","type":0,"val":"admin","end":""},{"old":"/admin/posts/:id","type":0,"val":"posts","end":""},{"old":"/admin/posts/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.posts.destroy']['types'],
  },
  'admin.taxonomies.index': {
    methods: ["GET","HEAD"],
    pattern: '/admin/taxonomies',
    tokens: [{"old":"/admin/taxonomies","type":0,"val":"admin","end":""},{"old":"/admin/taxonomies","type":0,"val":"taxonomies","end":""}],
    types: placeholder as Registry['admin.taxonomies.index']['types'],
  },
  'admin.taxonomies.create': {
    methods: ["GET","HEAD"],
    pattern: '/admin/taxonomies/create',
    tokens: [{"old":"/admin/taxonomies/create","type":0,"val":"admin","end":""},{"old":"/admin/taxonomies/create","type":0,"val":"taxonomies","end":""},{"old":"/admin/taxonomies/create","type":0,"val":"create","end":""}],
    types: placeholder as Registry['admin.taxonomies.create']['types'],
  },
  'admin.taxonomies.store': {
    methods: ["POST"],
    pattern: '/admin/taxonomies',
    tokens: [{"old":"/admin/taxonomies","type":0,"val":"admin","end":""},{"old":"/admin/taxonomies","type":0,"val":"taxonomies","end":""}],
    types: placeholder as Registry['admin.taxonomies.store']['types'],
  },
  'admin.taxonomies.edit': {
    methods: ["GET","HEAD"],
    pattern: '/admin/taxonomies/:id/edit',
    tokens: [{"old":"/admin/taxonomies/:id/edit","type":0,"val":"admin","end":""},{"old":"/admin/taxonomies/:id/edit","type":0,"val":"taxonomies","end":""},{"old":"/admin/taxonomies/:id/edit","type":1,"val":"id","end":""},{"old":"/admin/taxonomies/:id/edit","type":0,"val":"edit","end":""}],
    types: placeholder as Registry['admin.taxonomies.edit']['types'],
  },
  'admin.taxonomies.update': {
    methods: ["PUT","PATCH"],
    pattern: '/admin/taxonomies/:id',
    tokens: [{"old":"/admin/taxonomies/:id","type":0,"val":"admin","end":""},{"old":"/admin/taxonomies/:id","type":0,"val":"taxonomies","end":""},{"old":"/admin/taxonomies/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.taxonomies.update']['types'],
  },
  'admin.taxonomies.destroy': {
    methods: ["DELETE"],
    pattern: '/admin/taxonomies/:id',
    tokens: [{"old":"/admin/taxonomies/:id","type":0,"val":"admin","end":""},{"old":"/admin/taxonomies/:id","type":0,"val":"taxonomies","end":""},{"old":"/admin/taxonomies/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.taxonomies.destroy']['types'],
  },
  'admin.taxonomies.api_index': {
    methods: ["GET","HEAD"],
    pattern: '/admin/api/taxonomies',
    tokens: [{"old":"/admin/api/taxonomies","type":0,"val":"admin","end":""},{"old":"/admin/api/taxonomies","type":0,"val":"api","end":""},{"old":"/admin/api/taxonomies","type":0,"val":"taxonomies","end":""}],
    types: placeholder as Registry['admin.taxonomies.api_index']['types'],
  },
  'admin.taxonomy_contents.edit': {
    methods: ["GET","HEAD"],
    pattern: '/admin/taxonomies/:id/content',
    tokens: [{"old":"/admin/taxonomies/:id/content","type":0,"val":"admin","end":""},{"old":"/admin/taxonomies/:id/content","type":0,"val":"taxonomies","end":""},{"old":"/admin/taxonomies/:id/content","type":1,"val":"id","end":""},{"old":"/admin/taxonomies/:id/content","type":0,"val":"content","end":""}],
    types: placeholder as Registry['admin.taxonomy_contents.edit']['types'],
  },
  'admin.taxonomy_contents.update': {
    methods: ["PUT"],
    pattern: '/admin/taxonomies/:id/content',
    tokens: [{"old":"/admin/taxonomies/:id/content","type":0,"val":"admin","end":""},{"old":"/admin/taxonomies/:id/content","type":0,"val":"taxonomies","end":""},{"old":"/admin/taxonomies/:id/content","type":1,"val":"id","end":""},{"old":"/admin/taxonomies/:id/content","type":0,"val":"content","end":""}],
    types: placeholder as Registry['admin.taxonomy_contents.update']['types'],
  },
  'admin.users.index': {
    methods: ["GET","HEAD"],
    pattern: '/admin/users',
    tokens: [{"old":"/admin/users","type":0,"val":"admin","end":""},{"old":"/admin/users","type":0,"val":"users","end":""}],
    types: placeholder as Registry['admin.users.index']['types'],
  },
  'admin.users.show': {
    methods: ["GET","HEAD"],
    pattern: '/admin/users/:id',
    tokens: [{"old":"/admin/users/:id","type":0,"val":"admin","end":""},{"old":"/admin/users/:id","type":0,"val":"users","end":""},{"old":"/admin/users/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.users.show']['types'],
  },
  'admin.users.role': {
    methods: ["PATCH"],
    pattern: '/admin/users/:id/role',
    tokens: [{"old":"/admin/users/:id/role","type":0,"val":"admin","end":""},{"old":"/admin/users/:id/role","type":0,"val":"users","end":""},{"old":"/admin/users/:id/role","type":1,"val":"id","end":""},{"old":"/admin/users/:id/role","type":0,"val":"role","end":""}],
    types: placeholder as Registry['admin.users.role']['types'],
  },
  'admin.users.destroy': {
    methods: ["DELETE"],
    pattern: '/admin/users/:id',
    tokens: [{"old":"/admin/users/:id","type":0,"val":"admin","end":""},{"old":"/admin/users/:id","type":0,"val":"users","end":""},{"old":"/admin/users/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.users.destroy']['types'],
  },
  'admin.comments.index': {
    methods: ["GET","HEAD"],
    pattern: '/admin/comments',
    tokens: [{"old":"/admin/comments","type":0,"val":"admin","end":""},{"old":"/admin/comments","type":0,"val":"comments","end":""}],
    types: placeholder as Registry['admin.comments.index']['types'],
  },
  'admin.comments.destroy': {
    methods: ["DELETE"],
    pattern: '/admin/comments/:id',
    tokens: [{"old":"/admin/comments/:id","type":0,"val":"admin","end":""},{"old":"/admin/comments/:id","type":0,"val":"comments","end":""},{"old":"/admin/comments/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.comments.destroy']['types'],
  },
  'admin.discussions.index': {
    methods: ["GET","HEAD"],
    pattern: '/admin/discussions',
    tokens: [{"old":"/admin/discussions","type":0,"val":"admin","end":""},{"old":"/admin/discussions","type":0,"val":"discussions","end":""}],
    types: placeholder as Registry['admin.discussions.index']['types'],
  },
  'admin.discussions.destroy': {
    methods: ["DELETE"],
    pattern: '/admin/discussions/:id',
    tokens: [{"old":"/admin/discussions/:id","type":0,"val":"admin","end":""},{"old":"/admin/discussions/:id","type":0,"val":"discussions","end":""},{"old":"/admin/discussions/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.discussions.destroy']['types'],
  },
  'admin.roles.index': {
    methods: ["GET","HEAD"],
    pattern: '/admin/roles',
    tokens: [{"old":"/admin/roles","type":0,"val":"admin","end":""},{"old":"/admin/roles","type":0,"val":"roles","end":""}],
    types: placeholder as Registry['admin.roles.index']['types'],
  },
  'admin.roles.create': {
    methods: ["GET","HEAD"],
    pattern: '/admin/roles/create',
    tokens: [{"old":"/admin/roles/create","type":0,"val":"admin","end":""},{"old":"/admin/roles/create","type":0,"val":"roles","end":""},{"old":"/admin/roles/create","type":0,"val":"create","end":""}],
    types: placeholder as Registry['admin.roles.create']['types'],
  },
  'admin.roles.store': {
    methods: ["POST"],
    pattern: '/admin/roles',
    tokens: [{"old":"/admin/roles","type":0,"val":"admin","end":""},{"old":"/admin/roles","type":0,"val":"roles","end":""}],
    types: placeholder as Registry['admin.roles.store']['types'],
  },
  'admin.roles.edit': {
    methods: ["GET","HEAD"],
    pattern: '/admin/roles/:id/edit',
    tokens: [{"old":"/admin/roles/:id/edit","type":0,"val":"admin","end":""},{"old":"/admin/roles/:id/edit","type":0,"val":"roles","end":""},{"old":"/admin/roles/:id/edit","type":1,"val":"id","end":""},{"old":"/admin/roles/:id/edit","type":0,"val":"edit","end":""}],
    types: placeholder as Registry['admin.roles.edit']['types'],
  },
  'admin.roles.update': {
    methods: ["PUT","PATCH"],
    pattern: '/admin/roles/:id',
    tokens: [{"old":"/admin/roles/:id","type":0,"val":"admin","end":""},{"old":"/admin/roles/:id","type":0,"val":"roles","end":""},{"old":"/admin/roles/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.roles.update']['types'],
  },
  'admin.roles.destroy': {
    methods: ["DELETE"],
    pattern: '/admin/roles/:id',
    tokens: [{"old":"/admin/roles/:id","type":0,"val":"admin","end":""},{"old":"/admin/roles/:id","type":0,"val":"roles","end":""},{"old":"/admin/roles/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.roles.destroy']['types'],
  },
  'admin.roles': {
    methods: ["GET","HEAD"],
    pattern: '/admin/all-roles',
    tokens: [{"old":"/admin/all-roles","type":0,"val":"admin","end":""},{"old":"/admin/all-roles","type":0,"val":"all-roles","end":""}],
    types: placeholder as Registry['admin.roles']['types'],
  },
  'admin.assets.index': {
    methods: ["GET","HEAD"],
    pattern: '/admin/assets',
    tokens: [{"old":"/admin/assets","type":0,"val":"admin","end":""},{"old":"/admin/assets","type":0,"val":"assets","end":""}],
    types: placeholder as Registry['admin.assets.index']['types'],
  },
  'admin.assets.api_index': {
    methods: ["GET","HEAD"],
    pattern: '/admin/api/assets',
    tokens: [{"old":"/admin/api/assets","type":0,"val":"admin","end":""},{"old":"/admin/api/assets","type":0,"val":"api","end":""},{"old":"/admin/api/assets","type":0,"val":"assets","end":""}],
    types: placeholder as Registry['admin.assets.api_index']['types'],
  },
  'admin.assets.store': {
    methods: ["POST"],
    pattern: '/admin/assets',
    tokens: [{"old":"/admin/assets","type":0,"val":"admin","end":""},{"old":"/admin/assets","type":0,"val":"assets","end":""}],
    types: placeholder as Registry['admin.assets.store']['types'],
  },
  'admin.assets.destroy': {
    methods: ["DELETE"],
    pattern: '/admin/assets/:id',
    tokens: [{"old":"/admin/assets/:id","type":0,"val":"admin","end":""},{"old":"/admin/assets/:id","type":0,"val":"assets","end":""},{"old":"/admin/assets/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.assets.destroy']['types'],
  },
  'admin.courses.index': {
    methods: ["GET","HEAD"],
    pattern: '/admin/courses',
    tokens: [{"old":"/admin/courses","type":0,"val":"admin","end":""},{"old":"/admin/courses","type":0,"val":"courses","end":""}],
    types: placeholder as Registry['admin.courses.index']['types'],
  },
  'admin.courses.create': {
    methods: ["GET","HEAD"],
    pattern: '/admin/courses/create',
    tokens: [{"old":"/admin/courses/create","type":0,"val":"admin","end":""},{"old":"/admin/courses/create","type":0,"val":"courses","end":""},{"old":"/admin/courses/create","type":0,"val":"create","end":""}],
    types: placeholder as Registry['admin.courses.create']['types'],
  },
  'admin.courses.store': {
    methods: ["POST"],
    pattern: '/admin/courses',
    tokens: [{"old":"/admin/courses","type":0,"val":"admin","end":""},{"old":"/admin/courses","type":0,"val":"courses","end":""}],
    types: placeholder as Registry['admin.courses.store']['types'],
  },
  'admin.courses.edit': {
    methods: ["GET","HEAD"],
    pattern: '/admin/courses/:id/edit',
    tokens: [{"old":"/admin/courses/:id/edit","type":0,"val":"admin","end":""},{"old":"/admin/courses/:id/edit","type":0,"val":"courses","end":""},{"old":"/admin/courses/:id/edit","type":1,"val":"id","end":""},{"old":"/admin/courses/:id/edit","type":0,"val":"edit","end":""}],
    types: placeholder as Registry['admin.courses.edit']['types'],
  },
  'admin.courses.update': {
    methods: ["PUT","PATCH"],
    pattern: '/admin/courses/:id',
    tokens: [{"old":"/admin/courses/:id","type":0,"val":"admin","end":""},{"old":"/admin/courses/:id","type":0,"val":"courses","end":""},{"old":"/admin/courses/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.courses.update']['types'],
  },
  'admin.courses.destroy': {
    methods: ["DELETE"],
    pattern: '/admin/courses/:id',
    tokens: [{"old":"/admin/courses/:id","type":0,"val":"admin","end":""},{"old":"/admin/courses/:id","type":0,"val":"courses","end":""},{"old":"/admin/courses/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.courses.destroy']['types'],
  },
  'admin.courses.store_module': {
    methods: ["POST"],
    pattern: '/admin/courses/:id/modules',
    tokens: [{"old":"/admin/courses/:id/modules","type":0,"val":"admin","end":""},{"old":"/admin/courses/:id/modules","type":0,"val":"courses","end":""},{"old":"/admin/courses/:id/modules","type":1,"val":"id","end":""},{"old":"/admin/courses/:id/modules","type":0,"val":"modules","end":""}],
    types: placeholder as Registry['admin.courses.store_module']['types'],
  },
  'admin.courses.update_module': {
    methods: ["PUT"],
    pattern: '/admin/courses/:courseId/modules/:moduleId',
    tokens: [{"old":"/admin/courses/:courseId/modules/:moduleId","type":0,"val":"admin","end":""},{"old":"/admin/courses/:courseId/modules/:moduleId","type":0,"val":"courses","end":""},{"old":"/admin/courses/:courseId/modules/:moduleId","type":1,"val":"courseId","end":""},{"old":"/admin/courses/:courseId/modules/:moduleId","type":0,"val":"modules","end":""},{"old":"/admin/courses/:courseId/modules/:moduleId","type":1,"val":"moduleId","end":""}],
    types: placeholder as Registry['admin.courses.update_module']['types'],
  },
  'admin.courses.destroy_module': {
    methods: ["DELETE"],
    pattern: '/admin/courses/:courseId/modules/:moduleId',
    tokens: [{"old":"/admin/courses/:courseId/modules/:moduleId","type":0,"val":"admin","end":""},{"old":"/admin/courses/:courseId/modules/:moduleId","type":0,"val":"courses","end":""},{"old":"/admin/courses/:courseId/modules/:moduleId","type":1,"val":"courseId","end":""},{"old":"/admin/courses/:courseId/modules/:moduleId","type":0,"val":"modules","end":""},{"old":"/admin/courses/:courseId/modules/:moduleId","type":1,"val":"moduleId","end":""}],
    types: placeholder as Registry['admin.courses.destroy_module']['types'],
  },
  'admin.courses.update_module_content': {
    methods: ["PUT"],
    pattern: '/admin/courses/:courseId/modules/:moduleId/content',
    tokens: [{"old":"/admin/courses/:courseId/modules/:moduleId/content","type":0,"val":"admin","end":""},{"old":"/admin/courses/:courseId/modules/:moduleId/content","type":0,"val":"courses","end":""},{"old":"/admin/courses/:courseId/modules/:moduleId/content","type":1,"val":"courseId","end":""},{"old":"/admin/courses/:courseId/modules/:moduleId/content","type":0,"val":"modules","end":""},{"old":"/admin/courses/:courseId/modules/:moduleId/content","type":1,"val":"moduleId","end":""},{"old":"/admin/courses/:courseId/modules/:moduleId/content","type":0,"val":"content","end":""}],
    types: placeholder as Registry['admin.courses.update_module_content']['types'],
  },
  'admin.courses.reorder_modules': {
    methods: ["PUT"],
    pattern: '/admin/courses/:id/modules/order',
    tokens: [{"old":"/admin/courses/:id/modules/order","type":0,"val":"admin","end":""},{"old":"/admin/courses/:id/modules/order","type":0,"val":"courses","end":""},{"old":"/admin/courses/:id/modules/order","type":1,"val":"id","end":""},{"old":"/admin/courses/:id/modules/order","type":0,"val":"modules","end":""},{"old":"/admin/courses/:id/modules/order","type":0,"val":"order","end":""}],
    types: placeholder as Registry['admin.courses.reorder_modules']['types'],
  },
  'admin.series.index': {
    methods: ["GET","HEAD"],
    pattern: '/admin/series',
    tokens: [{"old":"/admin/series","type":0,"val":"admin","end":""},{"old":"/admin/series","type":0,"val":"series","end":""}],
    types: placeholder as Registry['admin.series.index']['types'],
  },
  'admin.series.create': {
    methods: ["GET","HEAD"],
    pattern: '/admin/series/create',
    tokens: [{"old":"/admin/series/create","type":0,"val":"admin","end":""},{"old":"/admin/series/create","type":0,"val":"series","end":""},{"old":"/admin/series/create","type":0,"val":"create","end":""}],
    types: placeholder as Registry['admin.series.create']['types'],
  },
  'admin.series.store': {
    methods: ["POST"],
    pattern: '/admin/series',
    tokens: [{"old":"/admin/series","type":0,"val":"admin","end":""},{"old":"/admin/series","type":0,"val":"series","end":""}],
    types: placeholder as Registry['admin.series.store']['types'],
  },
  'admin.series.edit': {
    methods: ["GET","HEAD"],
    pattern: '/admin/series/:id/edit',
    tokens: [{"old":"/admin/series/:id/edit","type":0,"val":"admin","end":""},{"old":"/admin/series/:id/edit","type":0,"val":"series","end":""},{"old":"/admin/series/:id/edit","type":1,"val":"id","end":""},{"old":"/admin/series/:id/edit","type":0,"val":"edit","end":""}],
    types: placeholder as Registry['admin.series.edit']['types'],
  },
  'admin.series.update': {
    methods: ["PUT","PATCH"],
    pattern: '/admin/series/:id',
    tokens: [{"old":"/admin/series/:id","type":0,"val":"admin","end":""},{"old":"/admin/series/:id","type":0,"val":"series","end":""},{"old":"/admin/series/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.series.update']['types'],
  },
  'admin.series.destroy': {
    methods: ["DELETE"],
    pattern: '/admin/series/:id',
    tokens: [{"old":"/admin/series/:id","type":0,"val":"admin","end":""},{"old":"/admin/series/:id","type":0,"val":"series","end":""},{"old":"/admin/series/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.series.destroy']['types'],
  },
  'admin.series.store_post': {
    methods: ["POST"],
    pattern: '/admin/series/:id/posts',
    tokens: [{"old":"/admin/series/:id/posts","type":0,"val":"admin","end":""},{"old":"/admin/series/:id/posts","type":0,"val":"series","end":""},{"old":"/admin/series/:id/posts","type":1,"val":"id","end":""},{"old":"/admin/series/:id/posts","type":0,"val":"posts","end":""}],
    types: placeholder as Registry['admin.series.store_post']['types'],
  },
  'admin.series.reorder_posts': {
    methods: ["PUT"],
    pattern: '/admin/series/:id/posts/order',
    tokens: [{"old":"/admin/series/:id/posts/order","type":0,"val":"admin","end":""},{"old":"/admin/series/:id/posts/order","type":0,"val":"series","end":""},{"old":"/admin/series/:id/posts/order","type":1,"val":"id","end":""},{"old":"/admin/series/:id/posts/order","type":0,"val":"posts","end":""},{"old":"/admin/series/:id/posts/order","type":0,"val":"order","end":""}],
    types: placeholder as Registry['admin.series.reorder_posts']['types'],
  },
  'admin.series.destroy_post': {
    methods: ["DELETE"],
    pattern: '/admin/series/:seriesId/posts/:postId',
    tokens: [{"old":"/admin/series/:seriesId/posts/:postId","type":0,"val":"admin","end":""},{"old":"/admin/series/:seriesId/posts/:postId","type":0,"val":"series","end":""},{"old":"/admin/series/:seriesId/posts/:postId","type":1,"val":"seriesId","end":""},{"old":"/admin/series/:seriesId/posts/:postId","type":0,"val":"posts","end":""},{"old":"/admin/series/:seriesId/posts/:postId","type":1,"val":"postId","end":""}],
    types: placeholder as Registry['admin.series.destroy_post']['types'],
  },
  'admin.playlists.index': {
    methods: ["GET","HEAD"],
    pattern: '/admin/playlists',
    tokens: [{"old":"/admin/playlists","type":0,"val":"admin","end":""},{"old":"/admin/playlists","type":0,"val":"playlists","end":""}],
    types: placeholder as Registry['admin.playlists.index']['types'],
  },
  'admin.playlists.create': {
    methods: ["GET","HEAD"],
    pattern: '/admin/playlists/create',
    tokens: [{"old":"/admin/playlists/create","type":0,"val":"admin","end":""},{"old":"/admin/playlists/create","type":0,"val":"playlists","end":""},{"old":"/admin/playlists/create","type":0,"val":"create","end":""}],
    types: placeholder as Registry['admin.playlists.create']['types'],
  },
  'admin.playlists.store': {
    methods: ["POST"],
    pattern: '/admin/playlists',
    tokens: [{"old":"/admin/playlists","type":0,"val":"admin","end":""},{"old":"/admin/playlists","type":0,"val":"playlists","end":""}],
    types: placeholder as Registry['admin.playlists.store']['types'],
  },
  'admin.playlists.edit': {
    methods: ["GET","HEAD"],
    pattern: '/admin/playlists/:id/edit',
    tokens: [{"old":"/admin/playlists/:id/edit","type":0,"val":"admin","end":""},{"old":"/admin/playlists/:id/edit","type":0,"val":"playlists","end":""},{"old":"/admin/playlists/:id/edit","type":1,"val":"id","end":""},{"old":"/admin/playlists/:id/edit","type":0,"val":"edit","end":""}],
    types: placeholder as Registry['admin.playlists.edit']['types'],
  },
  'admin.playlists.update': {
    methods: ["PUT","PATCH"],
    pattern: '/admin/playlists/:id',
    tokens: [{"old":"/admin/playlists/:id","type":0,"val":"admin","end":""},{"old":"/admin/playlists/:id","type":0,"val":"playlists","end":""},{"old":"/admin/playlists/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.playlists.update']['types'],
  },
  'admin.playlists.destroy': {
    methods: ["DELETE"],
    pattern: '/admin/playlists/:id',
    tokens: [{"old":"/admin/playlists/:id","type":0,"val":"admin","end":""},{"old":"/admin/playlists/:id","type":0,"val":"playlists","end":""},{"old":"/admin/playlists/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.playlists.destroy']['types'],
  },
  'admin.playlists.store_post': {
    methods: ["POST"],
    pattern: '/admin/playlists/:id/posts',
    tokens: [{"old":"/admin/playlists/:id/posts","type":0,"val":"admin","end":""},{"old":"/admin/playlists/:id/posts","type":0,"val":"playlists","end":""},{"old":"/admin/playlists/:id/posts","type":1,"val":"id","end":""},{"old":"/admin/playlists/:id/posts","type":0,"val":"posts","end":""}],
    types: placeholder as Registry['admin.playlists.store_post']['types'],
  },
  'admin.playlists.reorder_posts': {
    methods: ["PUT"],
    pattern: '/admin/playlists/:id/posts/order',
    tokens: [{"old":"/admin/playlists/:id/posts/order","type":0,"val":"admin","end":""},{"old":"/admin/playlists/:id/posts/order","type":0,"val":"playlists","end":""},{"old":"/admin/playlists/:id/posts/order","type":1,"val":"id","end":""},{"old":"/admin/playlists/:id/posts/order","type":0,"val":"posts","end":""},{"old":"/admin/playlists/:id/posts/order","type":0,"val":"order","end":""}],
    types: placeholder as Registry['admin.playlists.reorder_posts']['types'],
  },
  'admin.playlists.destroy_post': {
    methods: ["DELETE"],
    pattern: '/admin/playlists/:playlistId/posts/:postId',
    tokens: [{"old":"/admin/playlists/:playlistId/posts/:postId","type":0,"val":"admin","end":""},{"old":"/admin/playlists/:playlistId/posts/:postId","type":0,"val":"playlists","end":""},{"old":"/admin/playlists/:playlistId/posts/:postId","type":1,"val":"playlistId","end":""},{"old":"/admin/playlists/:playlistId/posts/:postId","type":0,"val":"posts","end":""},{"old":"/admin/playlists/:playlistId/posts/:postId","type":1,"val":"postId","end":""}],
    types: placeholder as Registry['admin.playlists.destroy_post']['types'],
  },
  'admin.paths.index': {
    methods: ["GET","HEAD"],
    pattern: '/admin/paths',
    tokens: [{"old":"/admin/paths","type":0,"val":"admin","end":""},{"old":"/admin/paths","type":0,"val":"paths","end":""}],
    types: placeholder as Registry['admin.paths.index']['types'],
  },
  'admin.paths.create': {
    methods: ["GET","HEAD"],
    pattern: '/admin/paths/create',
    tokens: [{"old":"/admin/paths/create","type":0,"val":"admin","end":""},{"old":"/admin/paths/create","type":0,"val":"paths","end":""},{"old":"/admin/paths/create","type":0,"val":"create","end":""}],
    types: placeholder as Registry['admin.paths.create']['types'],
  },
  'admin.paths.store': {
    methods: ["POST"],
    pattern: '/admin/paths',
    tokens: [{"old":"/admin/paths","type":0,"val":"admin","end":""},{"old":"/admin/paths","type":0,"val":"paths","end":""}],
    types: placeholder as Registry['admin.paths.store']['types'],
  },
  'admin.paths.edit': {
    methods: ["GET","HEAD"],
    pattern: '/admin/paths/:id/edit',
    tokens: [{"old":"/admin/paths/:id/edit","type":0,"val":"admin","end":""},{"old":"/admin/paths/:id/edit","type":0,"val":"paths","end":""},{"old":"/admin/paths/:id/edit","type":1,"val":"id","end":""},{"old":"/admin/paths/:id/edit","type":0,"val":"edit","end":""}],
    types: placeholder as Registry['admin.paths.edit']['types'],
  },
  'admin.paths.update': {
    methods: ["PUT","PATCH"],
    pattern: '/admin/paths/:id',
    tokens: [{"old":"/admin/paths/:id","type":0,"val":"admin","end":""},{"old":"/admin/paths/:id","type":0,"val":"paths","end":""},{"old":"/admin/paths/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.paths.update']['types'],
  },
  'admin.paths.destroy': {
    methods: ["DELETE"],
    pattern: '/admin/paths/:id',
    tokens: [{"old":"/admin/paths/:id","type":0,"val":"admin","end":""},{"old":"/admin/paths/:id","type":0,"val":"paths","end":""},{"old":"/admin/paths/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.paths.destroy']['types'],
  },
  'admin.paths.store_course': {
    methods: ["POST"],
    pattern: '/admin/paths/:id/courses',
    tokens: [{"old":"/admin/paths/:id/courses","type":0,"val":"admin","end":""},{"old":"/admin/paths/:id/courses","type":0,"val":"paths","end":""},{"old":"/admin/paths/:id/courses","type":1,"val":"id","end":""},{"old":"/admin/paths/:id/courses","type":0,"val":"courses","end":""}],
    types: placeholder as Registry['admin.paths.store_course']['types'],
  },
  'admin.paths.reorder_courses': {
    methods: ["PUT"],
    pattern: '/admin/paths/:id/courses/order',
    tokens: [{"old":"/admin/paths/:id/courses/order","type":0,"val":"admin","end":""},{"old":"/admin/paths/:id/courses/order","type":0,"val":"paths","end":""},{"old":"/admin/paths/:id/courses/order","type":1,"val":"id","end":""},{"old":"/admin/paths/:id/courses/order","type":0,"val":"courses","end":""},{"old":"/admin/paths/:id/courses/order","type":0,"val":"order","end":""}],
    types: placeholder as Registry['admin.paths.reorder_courses']['types'],
  },
  'admin.paths.destroy_course': {
    methods: ["DELETE"],
    pattern: '/admin/paths/:pathId/courses/:courseId',
    tokens: [{"old":"/admin/paths/:pathId/courses/:courseId","type":0,"val":"admin","end":""},{"old":"/admin/paths/:pathId/courses/:courseId","type":0,"val":"paths","end":""},{"old":"/admin/paths/:pathId/courses/:courseId","type":1,"val":"pathId","end":""},{"old":"/admin/paths/:pathId/courses/:courseId","type":0,"val":"courses","end":""},{"old":"/admin/paths/:pathId/courses/:courseId","type":1,"val":"courseId","end":""}],
    types: placeholder as Registry['admin.paths.destroy_course']['types'],
  },
  'admin.access_levels.index': {
    methods: ["GET","HEAD"],
    pattern: '/admin/access-levels',
    tokens: [{"old":"/admin/access-levels","type":0,"val":"admin","end":""},{"old":"/admin/access-levels","type":0,"val":"access-levels","end":""}],
    types: placeholder as Registry['admin.access_levels.index']['types'],
  },
  'admin.access_levels.create': {
    methods: ["GET","HEAD"],
    pattern: '/admin/access-levels/create',
    tokens: [{"old":"/admin/access-levels/create","type":0,"val":"admin","end":""},{"old":"/admin/access-levels/create","type":0,"val":"access-levels","end":""},{"old":"/admin/access-levels/create","type":0,"val":"create","end":""}],
    types: placeholder as Registry['admin.access_levels.create']['types'],
  },
  'admin.access_levels.store': {
    methods: ["POST"],
    pattern: '/admin/access-levels',
    tokens: [{"old":"/admin/access-levels","type":0,"val":"admin","end":""},{"old":"/admin/access-levels","type":0,"val":"access-levels","end":""}],
    types: placeholder as Registry['admin.access_levels.store']['types'],
  },
  'admin.access_levels.edit': {
    methods: ["GET","HEAD"],
    pattern: '/admin/access-levels/:id/edit',
    tokens: [{"old":"/admin/access-levels/:id/edit","type":0,"val":"admin","end":""},{"old":"/admin/access-levels/:id/edit","type":0,"val":"access-levels","end":""},{"old":"/admin/access-levels/:id/edit","type":1,"val":"id","end":""},{"old":"/admin/access-levels/:id/edit","type":0,"val":"edit","end":""}],
    types: placeholder as Registry['admin.access_levels.edit']['types'],
  },
  'admin.access_levels.update': {
    methods: ["PUT","PATCH"],
    pattern: '/admin/access-levels/:id',
    tokens: [{"old":"/admin/access-levels/:id","type":0,"val":"admin","end":""},{"old":"/admin/access-levels/:id","type":0,"val":"access-levels","end":""},{"old":"/admin/access-levels/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.access_levels.update']['types'],
  },
  'admin.access_levels.destroy': {
    methods: ["DELETE"],
    pattern: '/admin/access-levels/:id',
    tokens: [{"old":"/admin/access-levels/:id","type":0,"val":"admin","end":""},{"old":"/admin/access-levels/:id","type":0,"val":"access-levels","end":""},{"old":"/admin/access-levels/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.access_levels.destroy']['types'],
  },
  'admin.access_levels.reorder': {
    methods: ["PUT"],
    pattern: '/admin/access-levels/order',
    tokens: [{"old":"/admin/access-levels/order","type":0,"val":"admin","end":""},{"old":"/admin/access-levels/order","type":0,"val":"access-levels","end":""},{"old":"/admin/access-levels/order","type":0,"val":"order","end":""}],
    types: placeholder as Registry['admin.access_levels.reorder']['types'],
  },
  'admin.settings.index': {
    methods: ["GET","HEAD"],
    pattern: '/admin/settings',
    tokens: [{"old":"/admin/settings","type":0,"val":"admin","end":""},{"old":"/admin/settings","type":0,"val":"settings","end":""}],
    types: placeholder as Registry['admin.settings.index']['types'],
  },
  'admin.settings.update': {
    methods: ["POST"],
    pattern: '/admin/settings',
    tokens: [{"old":"/admin/settings","type":0,"val":"admin","end":""},{"old":"/admin/settings","type":0,"val":"settings","end":""}],
    types: placeholder as Registry['admin.settings.update']['types'],
  },
  'admin.ai.video_chapters': {
    methods: ["POST"],
    pattern: '/admin/ai/videos/:videoId/chapters',
    tokens: [{"old":"/admin/ai/videos/:videoId/chapters","type":0,"val":"admin","end":""},{"old":"/admin/ai/videos/:videoId/chapters","type":0,"val":"ai","end":""},{"old":"/admin/ai/videos/:videoId/chapters","type":0,"val":"videos","end":""},{"old":"/admin/ai/videos/:videoId/chapters","type":1,"val":"videoId","end":""},{"old":"/admin/ai/videos/:videoId/chapters","type":0,"val":"chapters","end":""}],
    types: placeholder as Registry['admin.ai.video_chapters']['types'],
  },
  'admin.ai.body_overview': {
    methods: ["POST"],
    pattern: '/admin/ai/lessons/:lessonId/body-overview',
    tokens: [{"old":"/admin/ai/lessons/:lessonId/body-overview","type":0,"val":"admin","end":""},{"old":"/admin/ai/lessons/:lessonId/body-overview","type":0,"val":"ai","end":""},{"old":"/admin/ai/lessons/:lessonId/body-overview","type":0,"val":"lessons","end":""},{"old":"/admin/ai/lessons/:lessonId/body-overview","type":1,"val":"lessonId","end":""},{"old":"/admin/ai/lessons/:lessonId/body-overview","type":0,"val":"body-overview","end":""}],
    types: placeholder as Registry['admin.ai.body_overview']['types'],
  },
  'admin.memberEnrollments.index': {
    methods: ["GET","HEAD"],
    pattern: '/admin/member-enrollments',
    tokens: [{"old":"/admin/member-enrollments","type":0,"val":"admin","end":""},{"old":"/admin/member-enrollments","type":0,"val":"member-enrollments","end":""}],
    types: placeholder as Registry['admin.memberEnrollments.index']['types'],
  },
  'admin.memberEnrollments.show': {
    methods: ["GET","HEAD"],
    pattern: '/admin/member-enrollments/:id',
    tokens: [{"old":"/admin/member-enrollments/:id","type":0,"val":"admin","end":""},{"old":"/admin/member-enrollments/:id","type":0,"val":"member-enrollments","end":""},{"old":"/admin/member-enrollments/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.memberEnrollments.show']['types'],
  },
  'admin.memberEnrollments.approve': {
    methods: ["POST"],
    pattern: '/admin/member-enrollments/:id/approve',
    tokens: [{"old":"/admin/member-enrollments/:id/approve","type":0,"val":"admin","end":""},{"old":"/admin/member-enrollments/:id/approve","type":0,"val":"member-enrollments","end":""},{"old":"/admin/member-enrollments/:id/approve","type":1,"val":"id","end":""},{"old":"/admin/member-enrollments/:id/approve","type":0,"val":"approve","end":""}],
    types: placeholder as Registry['admin.memberEnrollments.approve']['types'],
  },
  'admin.memberEnrollments.reject': {
    methods: ["POST"],
    pattern: '/admin/member-enrollments/:id/reject',
    tokens: [{"old":"/admin/member-enrollments/:id/reject","type":0,"val":"admin","end":""},{"old":"/admin/member-enrollments/:id/reject","type":0,"val":"member-enrollments","end":""},{"old":"/admin/member-enrollments/:id/reject","type":1,"val":"id","end":""},{"old":"/admin/member-enrollments/:id/reject","type":0,"val":"reject","end":""}],
    types: placeholder as Registry['admin.memberEnrollments.reject']['types'],
  },
  'admin.memberEnrollments.revoke': {
    methods: ["POST"],
    pattern: '/admin/member-enrollments/:id/revoke',
    tokens: [{"old":"/admin/member-enrollments/:id/revoke","type":0,"val":"admin","end":""},{"old":"/admin/member-enrollments/:id/revoke","type":0,"val":"member-enrollments","end":""},{"old":"/admin/member-enrollments/:id/revoke","type":1,"val":"id","end":""},{"old":"/admin/member-enrollments/:id/revoke","type":0,"val":"revoke","end":""}],
    types: placeholder as Registry['admin.memberEnrollments.revoke']['types'],
  },
  'admin.candidates.index': {
    methods: ["GET","HEAD"],
    pattern: '/admin/candidates',
    tokens: [{"old":"/admin/candidates","type":0,"val":"admin","end":""},{"old":"/admin/candidates","type":0,"val":"candidates","end":""}],
    types: placeholder as Registry['admin.candidates.index']['types'],
  },
  'admin.candidates.show': {
    methods: ["GET","HEAD"],
    pattern: '/admin/candidates/:id',
    tokens: [{"old":"/admin/candidates/:id","type":0,"val":"admin","end":""},{"old":"/admin/candidates/:id","type":0,"val":"candidates","end":""},{"old":"/admin/candidates/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.candidates.show']['types'],
  },
  'admin.candidates.approve': {
    methods: ["POST"],
    pattern: '/admin/candidates/:id/approve',
    tokens: [{"old":"/admin/candidates/:id/approve","type":0,"val":"admin","end":""},{"old":"/admin/candidates/:id/approve","type":0,"val":"candidates","end":""},{"old":"/admin/candidates/:id/approve","type":1,"val":"id","end":""},{"old":"/admin/candidates/:id/approve","type":0,"val":"approve","end":""}],
    types: placeholder as Registry['admin.candidates.approve']['types'],
  },
  'admin.candidates.reject': {
    methods: ["POST"],
    pattern: '/admin/candidates/:id/reject',
    tokens: [{"old":"/admin/candidates/:id/reject","type":0,"val":"admin","end":""},{"old":"/admin/candidates/:id/reject","type":0,"val":"candidates","end":""},{"old":"/admin/candidates/:id/reject","type":1,"val":"id","end":""},{"old":"/admin/candidates/:id/reject","type":0,"val":"reject","end":""}],
    types: placeholder as Registry['admin.candidates.reject']['types'],
  },
  'admin.candidates.remark': {
    methods: ["POST"],
    pattern: '/admin/candidates/:id/remark',
    tokens: [{"old":"/admin/candidates/:id/remark","type":0,"val":"admin","end":""},{"old":"/admin/candidates/:id/remark","type":0,"val":"candidates","end":""},{"old":"/admin/candidates/:id/remark","type":1,"val":"id","end":""},{"old":"/admin/candidates/:id/remark","type":0,"val":"remark","end":""}],
    types: placeholder as Registry['admin.candidates.remark']['types'],
  },
  'home': {
    methods: ["GET","HEAD"],
    pattern: '/',
    tokens: [{"old":"/","type":0,"val":"/","end":""}],
    types: placeholder as Registry['home']['types'],
  },
  'new_account.create': {
    methods: ["GET","HEAD"],
    pattern: '/signup',
    tokens: [{"old":"/signup","type":0,"val":"signup","end":""}],
    types: placeholder as Registry['new_account.create']['types'],
  },
  'new_account.store': {
    methods: ["POST"],
    pattern: '/signup',
    tokens: [{"old":"/signup","type":0,"val":"signup","end":""}],
    types: placeholder as Registry['new_account.store']['types'],
  },
  'session.create': {
    methods: ["GET","HEAD"],
    pattern: '/login',
    tokens: [{"old":"/login","type":0,"val":"login","end":""}],
    types: placeholder as Registry['session.create']['types'],
  },
  'session.store': {
    methods: ["POST"],
    pattern: '/login',
    tokens: [{"old":"/login","type":0,"val":"login","end":""}],
    types: placeholder as Registry['session.store']['types'],
  },
  'forget_passwords.index': {
    methods: ["GET","HEAD"],
    pattern: '/forget-password',
    tokens: [{"old":"/forget-password","type":0,"val":"forget-password","end":""}],
    types: placeholder as Registry['forget_passwords.index']['types'],
  },
  'forget_passwords': {
    methods: ["POST"],
    pattern: '/forget-password',
    tokens: [{"old":"/forget-password","type":0,"val":"forget-password","end":""}],
    types: placeholder as Registry['forget_passwords']['types'],
  },
  'reset_passwords.index': {
    methods: ["GET","HEAD"],
    pattern: '/reset-password/:email',
    tokens: [{"old":"/reset-password/:email","type":0,"val":"reset-password","end":""},{"old":"/reset-password/:email","type":1,"val":"email","end":""}],
    types: placeholder as Registry['reset_passwords.index']['types'],
  },
  'reset_passwords': {
    methods: ["POST"],
    pattern: '/reset-password',
    tokens: [{"old":"/reset-password","type":0,"val":"reset-password","end":""}],
    types: placeholder as Registry['reset_passwords']['types'],
  },
  'auth.verify.notice': {
    methods: ["GET","HEAD"],
    pattern: '/verify-email',
    tokens: [{"old":"/verify-email","type":0,"val":"verify-email","end":""}],
    types: placeholder as Registry['auth.verify.notice']['types'],
  },
  'auth.verify.resend': {
    methods: ["POST"],
    pattern: '/verify-email/resend',
    tokens: [{"old":"/verify-email/resend","type":0,"val":"verify-email","end":""},{"old":"/verify-email/resend","type":0,"val":"resend","end":""}],
    types: placeholder as Registry['auth.verify.resend']['types'],
  },
  'auth.verify.handle': {
    methods: ["GET","HEAD"],
    pattern: '/verify-email/:email',
    tokens: [{"old":"/verify-email/:email","type":0,"val":"verify-email","end":""},{"old":"/verify-email/:email","type":1,"val":"email","end":""}],
    types: placeholder as Registry['auth.verify.handle']['types'],
  },
  'session.destroy': {
    methods: ["POST"],
    pattern: '/logout',
    tokens: [{"old":"/logout","type":0,"val":"logout","end":""}],
    types: placeholder as Registry['session.destroy']['types'],
  },
  'onboarding.index': {
    methods: ["GET","HEAD"],
    pattern: '/onboarding',
    tokens: [{"old":"/onboarding","type":0,"val":"onboarding","end":""}],
    types: placeholder as Registry['onboarding.index']['types'],
  },
  'onboarding.personalInfo': {
    methods: ["POST"],
    pattern: '/onboarding/personal-info',
    tokens: [{"old":"/onboarding/personal-info","type":0,"val":"onboarding","end":""},{"old":"/onboarding/personal-info","type":0,"val":"personal-info","end":""}],
    types: placeholder as Registry['onboarding.personalInfo']['types'],
  },
  'onboarding.documents.upload': {
    methods: ["POST"],
    pattern: '/onboarding/documents/:field',
    tokens: [{"old":"/onboarding/documents/:field","type":0,"val":"onboarding","end":""},{"old":"/onboarding/documents/:field","type":0,"val":"documents","end":""},{"old":"/onboarding/documents/:field","type":1,"val":"field","end":""}],
    types: placeholder as Registry['onboarding.documents.upload']['types'],
  },
  'onboarding.documents.remove': {
    methods: ["POST"],
    pattern: '/onboarding/documents/remove',
    tokens: [{"old":"/onboarding/documents/remove","type":0,"val":"onboarding","end":""},{"old":"/onboarding/documents/remove","type":0,"val":"documents","end":""},{"old":"/onboarding/documents/remove","type":0,"val":"remove","end":""}],
    types: placeholder as Registry['onboarding.documents.remove']['types'],
  },
  'onboarding.introVideo': {
    methods: ["POST"],
    pattern: '/onboarding/intro-video',
    tokens: [{"old":"/onboarding/intro-video","type":0,"val":"onboarding","end":""},{"old":"/onboarding/intro-video","type":0,"val":"intro-video","end":""}],
    types: placeholder as Registry['onboarding.introVideo']['types'],
  },
  'onboarding.kyc': {
    methods: ["POST"],
    pattern: '/onboarding/kyc',
    tokens: [{"old":"/onboarding/kyc","type":0,"val":"onboarding","end":""},{"old":"/onboarding/kyc","type":0,"val":"kyc","end":""}],
    types: placeholder as Registry['onboarding.kyc']['types'],
  },
  'onboarding.purpose': {
    methods: ["POST"],
    pattern: '/onboarding/purpose',
    tokens: [{"old":"/onboarding/purpose","type":0,"val":"onboarding","end":""},{"old":"/onboarding/purpose","type":0,"val":"purpose","end":""}],
    types: placeholder as Registry['onboarding.purpose']['types'],
  },
  'onboarding.submit': {
    methods: ["POST"],
    pattern: '/onboarding/submit',
    tokens: [{"old":"/onboarding/submit","type":0,"val":"onboarding","end":""},{"old":"/onboarding/submit","type":0,"val":"submit","end":""}],
    types: placeholder as Registry['onboarding.submit']['types'],
  },
  'application.status': {
    methods: ["GET","HEAD"],
    pattern: '/application/status',
    tokens: [{"old":"/application/status","type":0,"val":"application","end":""},{"old":"/application/status","type":0,"val":"status","end":""}],
    types: placeholder as Registry['application.status']['types'],
  },
  'series.index': {
    methods: ["GET","HEAD"],
    pattern: '/series',
    tokens: [{"old":"/series","type":0,"val":"series","end":""}],
    types: placeholder as Registry['series.index']['types'],
  },
  'series.show': {
    methods: ["GET","HEAD"],
    pattern: '/series/:slug',
    tokens: [{"old":"/series/:slug","type":0,"val":"series","end":""},{"old":"/series/:slug","type":1,"val":"slug","end":""}],
    types: placeholder as Registry['series.show']['types'],
  },
  'courses.show': {
    methods: ["GET","HEAD"],
    pattern: '/courses/:slug',
    tokens: [{"old":"/courses/:slug","type":0,"val":"courses","end":""},{"old":"/courses/:slug","type":1,"val":"slug","end":""}],
    types: placeholder as Registry['courses.show']['types'],
  },
  'memberEnrollments.index': {
    methods: ["GET","HEAD"],
    pattern: '/my-enrollments',
    tokens: [{"old":"/my-enrollments","type":0,"val":"my-enrollments","end":""}],
    types: placeholder as Registry['memberEnrollments.index']['types'],
  },
  'courses.memberEnrollments.store': {
    methods: ["POST"],
    pattern: '/courses/:slug/member-enrollments',
    tokens: [{"old":"/courses/:slug/member-enrollments","type":0,"val":"courses","end":""},{"old":"/courses/:slug/member-enrollments","type":1,"val":"slug","end":""},{"old":"/courses/:slug/member-enrollments","type":0,"val":"member-enrollments","end":""}],
    types: placeholder as Registry['courses.memberEnrollments.store']['types'],
  },
  'courses.memberEnrollments.update': {
    methods: ["PATCH"],
    pattern: '/courses/:slug/member-enrollments/:id',
    tokens: [{"old":"/courses/:slug/member-enrollments/:id","type":0,"val":"courses","end":""},{"old":"/courses/:slug/member-enrollments/:id","type":1,"val":"slug","end":""},{"old":"/courses/:slug/member-enrollments/:id","type":0,"val":"member-enrollments","end":""},{"old":"/courses/:slug/member-enrollments/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['courses.memberEnrollments.update']['types'],
  },
  'series.memberEnrollments.store': {
    methods: ["POST"],
    pattern: '/series/:slug/member-enrollments',
    tokens: [{"old":"/series/:slug/member-enrollments","type":0,"val":"series","end":""},{"old":"/series/:slug/member-enrollments","type":1,"val":"slug","end":""},{"old":"/series/:slug/member-enrollments","type":0,"val":"member-enrollments","end":""}],
    types: placeholder as Registry['series.memberEnrollments.store']['types'],
  },
  'series.memberEnrollments.update': {
    methods: ["PATCH"],
    pattern: '/series/:slug/member-enrollments/:id',
    tokens: [{"old":"/series/:slug/member-enrollments/:id","type":0,"val":"series","end":""},{"old":"/series/:slug/member-enrollments/:id","type":1,"val":"slug","end":""},{"old":"/series/:slug/member-enrollments/:id","type":0,"val":"member-enrollments","end":""},{"old":"/series/:slug/member-enrollments/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['series.memberEnrollments.update']['types'],
  },
  'dashboard': {
    methods: ["GET","HEAD"],
    pattern: '/dashboard',
    tokens: [{"old":"/dashboard","type":0,"val":"dashboard","end":""}],
    types: placeholder as Registry['dashboard']['types'],
  },
  'my-progress': {
    methods: ["GET","HEAD"],
    pattern: '/my-progress',
    tokens: [{"old":"/my-progress","type":0,"val":"my-progress","end":""}],
    types: placeholder as Registry['my-progress']['types'],
  },
  'lessons.index': {
    methods: ["GET","HEAD"],
    pattern: '/lessons',
    tokens: [{"old":"/lessons","type":0,"val":"lessons","end":""}],
    types: placeholder as Registry['lessons.index']['types'],
  },
  'lessons.setDefaultPanel': {
    methods: ["PATCH"],
    pattern: '/lessons/set-default-panel',
    tokens: [{"old":"/lessons/set-default-panel","type":0,"val":"lessons","end":""},{"old":"/lessons/set-default-panel","type":0,"val":"set-default-panel","end":""}],
    types: placeholder as Registry['lessons.setDefaultPanel']['types'],
  },
  'lessons.watchlist': {
    methods: ["PATCH"],
    pattern: '/lessons/:slug/watchlist',
    tokens: [{"old":"/lessons/:slug/watchlist","type":0,"val":"lessons","end":""},{"old":"/lessons/:slug/watchlist","type":1,"val":"slug","end":""},{"old":"/lessons/:slug/watchlist","type":0,"val":"watchlist","end":""}],
    types: placeholder as Registry['lessons.watchlist']['types'],
  },
  'lessons.autoplay': {
    methods: ["PATCH"],
    pattern: '/lessons/:slug/autoplay',
    tokens: [{"old":"/lessons/:slug/autoplay","type":0,"val":"lessons","end":""},{"old":"/lessons/:slug/autoplay","type":1,"val":"slug","end":""},{"old":"/lessons/:slug/autoplay","type":0,"val":"autoplay","end":""}],
    types: placeholder as Registry['lessons.autoplay']['types'],
  },
  'lessons.show': {
    methods: ["GET","HEAD"],
    pattern: '/lessons/:slug',
    tokens: [{"old":"/lessons/:slug","type":0,"val":"lessons","end":""},{"old":"/lessons/:slug","type":1,"val":"slug","end":""}],
    types: placeholder as Registry['lessons.show']['types'],
  },
  'lessons.assessment': {
    methods: ["GET","HEAD"],
    pattern: '/lessons/:slug/assessment',
    tokens: [{"old":"/lessons/:slug/assessment","type":0,"val":"lessons","end":""},{"old":"/lessons/:slug/assessment","type":1,"val":"slug","end":""},{"old":"/lessons/:slug/assessment","type":0,"val":"assessment","end":""}],
    types: placeholder as Registry['lessons.assessment']['types'],
  },
  'lessons.assessment.submit': {
    methods: ["POST"],
    pattern: '/lessons/:slug/assessment/submit',
    tokens: [{"old":"/lessons/:slug/assessment/submit","type":0,"val":"lessons","end":""},{"old":"/lessons/:slug/assessment/submit","type":1,"val":"slug","end":""},{"old":"/lessons/:slug/assessment/submit","type":0,"val":"assessment","end":""},{"old":"/lessons/:slug/assessment/submit","type":0,"val":"submit","end":""}],
    types: placeholder as Registry['lessons.assessment.submit']['types'],
  },
  'assessments.history': {
    methods: ["GET","HEAD"],
    pattern: '/api/assessments/history',
    tokens: [{"old":"/api/assessments/history","type":0,"val":"api","end":""},{"old":"/api/assessments/history","type":0,"val":"assessments","end":""},{"old":"/api/assessments/history","type":0,"val":"history","end":""}],
    types: placeholder as Registry['assessments.history']['types'],
  },
  'users.watchlist': {
    methods: ["GET","HEAD"],
    pattern: '/users/watchlist',
    tokens: [{"old":"/users/watchlist","type":0,"val":"users","end":""},{"old":"/users/watchlist","type":0,"val":"watchlist","end":""}],
    types: placeholder as Registry['users.watchlist']['types'],
  },
  'progress.store': {
    methods: ["POST"],
    pattern: '/progress',
    tokens: [{"old":"/progress","type":0,"val":"progress","end":""}],
    types: placeholder as Registry['progress.store']['types'],
  },
  'progress.toggle': {
    methods: ["PATCH"],
    pattern: '/progress/toggle',
    tokens: [{"old":"/progress/toggle","type":0,"val":"progress","end":""},{"old":"/progress/toggle","type":0,"val":"toggle","end":""}],
    types: placeholder as Registry['progress.toggle']['types'],
  },
  'settings.index': {
    methods: ["GET","HEAD"],
    pattern: '/settings',
    tokens: [{"old":"/settings","type":0,"val":"settings","end":""}],
    types: placeholder as Registry['settings.index']['types'],
  },
  'settings.show': {
    methods: ["GET","HEAD"],
    pattern: '/settings/:section',
    tokens: [{"old":"/settings/:section","type":0,"val":"settings","end":""},{"old":"/settings/:section","type":1,"val":"section","end":""}],
    types: placeholder as Registry['settings.show']['types'],
  },
  'settings.updateProfile': {
    methods: ["PUT"],
    pattern: '/settings/profile',
    tokens: [{"old":"/settings/profile","type":0,"val":"settings","end":""},{"old":"/settings/profile","type":0,"val":"profile","end":""}],
    types: placeholder as Registry['settings.updateProfile']['types'],
  },
  'settings.updateUsername': {
    methods: ["PUT"],
    pattern: '/settings/username',
    tokens: [{"old":"/settings/username","type":0,"val":"settings","end":""},{"old":"/settings/username","type":0,"val":"username","end":""}],
    types: placeholder as Registry['settings.updateUsername']['types'],
  },
  'settings.updateEmail': {
    methods: ["PUT"],
    pattern: '/settings/email',
    tokens: [{"old":"/settings/email","type":0,"val":"settings","end":""},{"old":"/settings/email","type":0,"val":"email","end":""}],
    types: placeholder as Registry['settings.updateEmail']['types'],
  },
  'settings.updatePassword': {
    methods: ["PUT"],
    pattern: '/settings/password',
    tokens: [{"old":"/settings/password","type":0,"val":"settings","end":""},{"old":"/settings/password","type":0,"val":"password","end":""}],
    types: placeholder as Registry['settings.updatePassword']['types'],
  },
  'settings.updateNotifications': {
    methods: ["PUT"],
    pattern: '/settings/notifications',
    tokens: [{"old":"/settings/notifications","type":0,"val":"settings","end":""},{"old":"/settings/notifications","type":0,"val":"notifications","end":""}],
    types: placeholder as Registry['settings.updateNotifications']['types'],
  },
  'settings.destroy': {
    methods: ["DELETE"],
    pattern: '/settings/account',
    tokens: [{"old":"/settings/account","type":0,"val":"settings","end":""},{"old":"/settings/account","type":0,"val":"account","end":""}],
    types: placeholder as Registry['settings.destroy']['types'],
  },
  'topics.index': {
    methods: ["GET","HEAD"],
    pattern: '/topics',
    tokens: [{"old":"/topics","type":0,"val":"topics","end":""}],
    types: placeholder as Registry['topics.index']['types'],
  },
  'topics.show': {
    methods: ["GET","HEAD"],
    pattern: '/topics/:slug',
    tokens: [{"old":"/topics/:slug","type":0,"val":"topics","end":""},{"old":"/topics/:slug","type":1,"val":"slug","end":""}],
    types: placeholder as Registry['topics.show']['types'],
  },
  'blogs.index': {
    methods: ["GET","HEAD"],
    pattern: '/blog',
    tokens: [{"old":"/blog","type":0,"val":"blog","end":""}],
    types: placeholder as Registry['blogs.index']['types'],
  },
  'blogs.show': {
    methods: ["GET","HEAD"],
    pattern: '/blog/:slug',
    tokens: [{"old":"/blog/:slug","type":0,"val":"blog","end":""},{"old":"/blog/:slug","type":1,"val":"slug","end":""}],
    types: placeholder as Registry['blogs.show']['types'],
  },
  'posts.index': {
    methods: ["GET","HEAD"],
    pattern: '/posts',
    tokens: [{"old":"/posts","type":0,"val":"posts","end":""}],
    types: placeholder as Registry['posts.index']['types'],
  },
  'posts.show': {
    methods: ["GET","HEAD"],
    pattern: '/posts/:slug',
    tokens: [{"old":"/posts/:slug","type":0,"val":"posts","end":""},{"old":"/posts/:slug","type":1,"val":"slug","end":""}],
    types: placeholder as Registry['posts.show']['types'],
  },
  'comments.store': {
    methods: ["POST"],
    pattern: '/comments',
    tokens: [{"old":"/comments","type":0,"val":"comments","end":""}],
    types: placeholder as Registry['comments.store']['types'],
  },
  'comments.update': {
    methods: ["PUT","PATCH"],
    pattern: '/comments/:id',
    tokens: [{"old":"/comments/:id","type":0,"val":"comments","end":""},{"old":"/comments/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['comments.update']['types'],
  },
  'comments.destroy': {
    methods: ["DELETE"],
    pattern: '/comments/:id',
    tokens: [{"old":"/comments/:id","type":0,"val":"comments","end":""},{"old":"/comments/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['comments.destroy']['types'],
  },
  'comments.toggleVote': {
    methods: ["POST"],
    pattern: '/comments/:id/vote',
    tokens: [{"old":"/comments/:id/vote","type":0,"val":"comments","end":""},{"old":"/comments/:id/vote","type":1,"val":"id","end":""},{"old":"/comments/:id/vote","type":0,"val":"vote","end":""}],
    types: placeholder as Registry['comments.toggleVote']['types'],
  },
  'discussions.index': {
    methods: ["GET","HEAD"],
    pattern: '/forum',
    tokens: [{"old":"/forum","type":0,"val":"forum","end":""}],
    types: placeholder as Registry['discussions.index']['types'],
  },
  'discussions.create': {
    methods: ["GET","HEAD"],
    pattern: '/forum/create',
    tokens: [{"old":"/forum/create","type":0,"val":"forum","end":""},{"old":"/forum/create","type":0,"val":"create","end":""}],
    types: placeholder as Registry['discussions.create']['types'],
  },
  'discussions.store': {
    methods: ["POST"],
    pattern: '/forum',
    tokens: [{"old":"/forum","type":0,"val":"forum","end":""}],
    types: placeholder as Registry['discussions.store']['types'],
  },
  'discussions.show': {
    methods: ["GET","HEAD"],
    pattern: '/forum/:slug',
    tokens: [{"old":"/forum/:slug","type":0,"val":"forum","end":""},{"old":"/forum/:slug","type":1,"val":"slug","end":""}],
    types: placeholder as Registry['discussions.show']['types'],
  },
  'discussions.edit': {
    methods: ["GET","HEAD"],
    pattern: '/forum/:slug/edit',
    tokens: [{"old":"/forum/:slug/edit","type":0,"val":"forum","end":""},{"old":"/forum/:slug/edit","type":1,"val":"slug","end":""},{"old":"/forum/:slug/edit","type":0,"val":"edit","end":""}],
    types: placeholder as Registry['discussions.edit']['types'],
  },
  'discussions.update': {
    methods: ["PUT"],
    pattern: '/forum/:slug',
    tokens: [{"old":"/forum/:slug","type":0,"val":"forum","end":""},{"old":"/forum/:slug","type":1,"val":"slug","end":""}],
    types: placeholder as Registry['discussions.update']['types'],
  },
  'discussions.destroy': {
    methods: ["DELETE"],
    pattern: '/forum/:slug',
    tokens: [{"old":"/forum/:slug","type":0,"val":"forum","end":""},{"old":"/forum/:slug","type":1,"val":"slug","end":""}],
    types: placeholder as Registry['discussions.destroy']['types'],
  },
  'discussions.toggleVote': {
    methods: ["POST"],
    pattern: '/forum/:id/vote',
    tokens: [{"old":"/forum/:id/vote","type":0,"val":"forum","end":""},{"old":"/forum/:id/vote","type":1,"val":"id","end":""},{"old":"/forum/:id/vote","type":0,"val":"vote","end":""}],
    types: placeholder as Registry['discussions.toggleVote']['types'],
  },
  'discussions.toggleSolved': {
    methods: ["POST"],
    pattern: '/forum/:slug/solved',
    tokens: [{"old":"/forum/:slug/solved","type":0,"val":"forum","end":""},{"old":"/forum/:slug/solved","type":1,"val":"slug","end":""},{"old":"/forum/:slug/solved","type":0,"val":"solved","end":""}],
    types: placeholder as Registry['discussions.toggleSolved']['types'],
  },
  'search': {
    methods: ["GET","HEAD"],
    pattern: '/search',
    tokens: [{"old":"/search","type":0,"val":"search","end":""}],
    types: placeholder as Registry['search']['types'],
  },
  'rss': {
    methods: ["GET","HEAD"],
    pattern: '/rss',
    tokens: [{"old":"/rss","type":0,"val":"rss","end":""}],
    types: placeholder as Registry['rss']['types'],
  },
  'sitemap': {
    methods: ["GET","HEAD"],
    pattern: '/sitemap.xml',
    tokens: [{"old":"/sitemap.xml","type":0,"val":"sitemap.xml","end":""}],
    types: placeholder as Registry['sitemap']['types'],
  },
  'profiles.show': {
    methods: ["GET","HEAD"],
    pattern: '/:handle',
    tokens: [{"old":"/:handle","type":1,"val":"handle","end":""}],
    types: placeholder as Registry['profiles.show']['types'],
  },
  'attachments': {
    methods: ["GET","HEAD"],
    pattern: '/attachments/:key/:name?',
    tokens: [{"old":"/attachments/:key/:name?","type":0,"val":"attachments","end":""},{"old":"/attachments/:key/:name?","type":1,"val":"key","end":""},{"old":"/attachments/:key/:name?","type":3,"val":"name","end":""}],
    types: placeholder as Registry['attachments']['types'],
  },
} as const satisfies Record<string, AdonisEndpoint>

export { routes }

export const registry = {
  routes,
  $tree: {} as ApiDefinition,
}

declare module '@tuyau/core/types' {
  export interface UserRegistry {
    routes: typeof routes
    $tree: ApiDefinition
  }
}
